"""
Training configuration for APD Intelligibility Estimator.
"""

from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional


@dataclass
class AudioConfig:
    sample_rate: int = 16000
    window_samples: int = 16000  # 1 second
    encoder_kernel: int = 40
    encoder_stride: int = 20


@dataclass
class DataConfig:
    # Paths (user must set these)
    librispeech_root: Path = Path("data/LibriSpeech")
    demand_root: Path = Path("data/DEMAND")
    dns_noise_root: Path = Path("data/dns_noise")

    # Manifest paths (generated by preprocessing)
    manifest_dir: Path = Path("data/manifests")
    train_manifest: str = "train.jsonl"
    val_manifest: str = "val.jsonl"
    test_manifest: str = "test.jsonl"

    # Dataset sizes
    n_train: int = 500_000
    n_val: int = 50_000
    n_test: int = 50_000

    # Workers
    num_workers: int = 4
    prefetch_factor: int = 2

    # Precomputed features cache
    cache_dir: Path = Path("data/cache")


@dataclass
class DegradationConfig:
    """Ranges for audio degradation parameters."""
    snr_range: tuple[float, float] = (-5.0, 30.0)
    rt60_range: tuple[float, float] = (0.0, 2.0)
    speech_rate_range: tuple[float, float] = (0.8, 1.5)

    # Masker type sampling weights (uniform by default)
    masker_weights: dict[str, float] = field(default_factory=lambda: {
        "none": 0.15,
        "stationary": 0.20,
        "modulated": 0.20,
        "babble_multi": 0.20,
        "competing_1_2": 0.25,  # slightly oversampled (APD worst case)
    })

    # Competing speaker SIR range
    sir_range: tuple[float, float] = (-5.0, 20.0)

    # Babble: number of speakers
    babble_speakers_range: tuple[int, int] = (4, 8)


@dataclass
class APDLabelConfig:
    """APD pseudo-label generation parameters (based on research)."""
    # STOI/PESQ blend
    stoi_weight: float = 0.6
    pesq_weight: float = 0.4

    # APD SNR penalty
    apd_snr_shift: float = 8.0        # dB, average APD SNR loss
    snr_sigmoid_center: float = 5.0   # dB
    snr_sigmoid_slope: float = 0.15

    # Masker type penalties
    masker_penalties: dict[str, float] = field(default_factory=lambda: {
        "none": 1.0,
        "stationary": 0.95,
        "modulated": 0.80,
        "babble_multi": 0.65,
        "competing_1_2": 0.45,
    })

    # Reverb penalty breakpoints
    rt60_optimal: float = 0.4
    rt60_moderate: float = 0.7

    # Label smoothing noise
    label_noise_sigma: float = 0.02


@dataclass
class AugmentationConfig:
    """Online augmentation during training."""
    gain_db_range: tuple[float, float] = (-3.0, 3.0)
    shift_ms_range: tuple[float, float] = (-50.0, 50.0)
    mixup_alpha: float = 0.2
    mixup_prob: float = 0.3


@dataclass
class TrainConfig:
    # Optimizer
    lr: float = 3e-4
    weight_decay: float = 0.01
    warmup_steps: int = 2000
    min_lr: float = 1e-6

    # Training
    batch_size: int = 32
    epochs: int = 50
    grad_clip_max_norm: float = 5.0

    # Early stopping
    patience: int = 10

    # Loss weights
    ranking_loss_weight: float = 0.1
    boundary_loss_weight: float = 0.05
    boundary_thresholds: list[float] = field(default_factory=lambda: [0.3, 0.5, 0.8])
    boundary_sigma: float = 0.05

    # Checkpointing
    checkpoint_dir: Path = Path("checkpoints")
    save_every_epochs: int = 5
    log_every_steps: int = 100

    # Device
    device: str = "cuda"

    # Seed
    seed: int = 42


@dataclass
class PruningConfig:
    n_rounds: int = 4
    prune_ratio_per_round: float = 0.15
    finetune_epochs_per_round: int = 10

    # Post-pruning retraining
    retrain_epochs: int = 25
    retrain_lr: float = 1e-4

    # Knowledge distillation
    distill_temperature: float = 4.0
    distill_alpha: float = 0.7  # weight for distillation loss vs task loss


@dataclass
class ExportConfig:
    output_path: Path = Path("model.apd")
    validate: bool = True
    n_validation_inputs: int = 100
    tolerance: float = 0.01


@dataclass
class Config:
    audio: AudioConfig = field(default_factory=AudioConfig)
    data: DataConfig = field(default_factory=DataConfig)
    degradation: DegradationConfig = field(default_factory=DegradationConfig)
    apd_label: APDLabelConfig = field(default_factory=APDLabelConfig)
    augmentation: AugmentationConfig = field(default_factory=AugmentationConfig)
    train: TrainConfig = field(default_factory=TrainConfig)
    pruning: PruningConfig = field(default_factory=PruningConfig)
    export: ExportConfig = field(default_factory=ExportConfig)
